import json

class CandidateRanker:
    def __init__(self, shortlist_threshold=75.0, review_threshold=50.0):
        # Define action zones based on HR requirements
        self.shortlist_threshold = shortlist_threshold
        self.review_threshold = review_threshold

    def _categorize_candidate(self, score):
        """Assigns the candidate to an actionable zone based on their final score."""
        if score >= self.shortlist_threshold:
            return "Auto-Shortlisted"
        elif score >= self.review_threshold:
            return "Manual Review"
        else:
            return "Auto-Rejected"

    def process_and_rank(self, candidates):
        """Sorts candidates by score in descending order and assigns ranks/zones."""
        if not candidates:
            return []

        # Sort candidates by final score (highest to lowest)
        ranked = sorted(candidates, key=lambda x: x.get('final_score', 0), reverse=True)
        
        # Assign rank numbers and zones
        for rank, candidate in enumerate(ranked, start=1):
            candidate['rank'] = rank
            candidate['zone'] = self._categorize_candidate(candidate.get('final_score', 0))
            
        return ranked

    def generate_recruiter_report(self, ranked_candidates, top_n=3):
        """Generates a structured, recruiter-friendly output summary."""
        report = {
            "summary": {
                "total_evaluated": len(ranked_candidates),
                "shortlisted_count": sum(1 for c in ranked_candidates if c['zone'] == "Auto-Shortlisted"),
                "review_count": sum(1 for c in ranked_candidates if c['zone'] == "Manual Review"),
                "rejected_count": sum(1 for c in ranked_candidates if c['zone'] == "Auto-Rejected")
            },
            # Extract just the top N candidates for immediate recruiter visibility
            "top_candidates": ranked_candidates[:top_n],
            "all_ranked_results": ranked_candidates
        }
        return report

# Test execution
if __name__ == "__main__":
    # Simulated batch of candidate scores generated by the Day 13 Scoring Engine
    sample_batch = [
        {"candidate_id": "cnd-001", "name": "Candidate A", "final_score": 45.2, "role": "Data Scientist"},
        {"candidate_id": "cnd-002", "name": "Candidate B", "final_score": 73.6, "role": "Data Scientist"},
        {"candidate_id": "cnd-003", "name": "Candidate C", "final_score": 89.1, "role": "Data Scientist"},
        {"candidate_id": "cnd-004", "name": "Candidate D", "final_score": 92.5, "role": "Data Scientist"},
        {"candidate_id": "cnd-005", "name": "Candidate E", "final_score": 62.0, "role": "Data Scientist"}
    ]
    
    # Initialize the ranker with default thresholds
    ranker = CandidateRanker(shortlist_threshold=75.0, review_threshold=50.0)
    
    # Process the batch
    ranked_list = ranker.process_and_rank(sample_batch)
    
    # Generate a report highlighting the Top 2 candidates
    final_report = ranker.generate_recruiter_report(ranked_list, top_n=2)
    
    print(json.dumps(final_report, indent=2))